version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
  - dependency-name: icalendar
    versions:
    - 2.7.0
